
// Action Types

export const TOGGLE_TABLE = "TOGGLE_TABLE";
export const TOGGLE_DIMENSION = "TOGGLE_DIMENSION";
export const TOGGLE_ROW = "TOGGLE_ROW";

export const CHANGE_FILTER_TEXT = "CHANGE_FILTER_TEXT";
export const CHANGE_FILTER_TYPE = "CHANGE_FILTER_TYPE";
export const TOGGLE_FILTER_SORT = "TOGGLE_FILTER_SORT";

export const TOGGLE_TABLES_POPUP = "TOGGLE_TABLES_POPUP";
export const TOGGLE_DIMENSIONS_POPUP = "TOGGLE_DIMENSIONS_POPUP";

// Async action types

export const FETCH_ENTITIES_REQUEST = "FETCH_ENTITIES";
export const FETCH_ENTITIES_SUCCESS = "FETCH_ENTITIES_SUCCESS";
export const FETCH_ENTITIES_ERROR = "FETCH_ENTITIES_ERROR";


